train:
  train_batch_size: 4096
  val_batch_size: 4096
  epochs: 100
  lr: 3.0e-4
  weight_decay: 0.01
  val_cap: 10
  data_scale: 4
nerf:
  sample_points: 64
model:
  num_layers: 10
  d_model: 256
  pe_l: 10
